# Generated by Django 3.1.7 on 2021-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MedRec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
