# Generated by Django 3.1.7 on 2021-05-17 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('symptoms', models.CharField(max_length=500)),
                ('prescription', models.TextField()),
                ('doctor',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_prescription',
                                   to=settings.AUTH_USER_MODEL)),
                ('patient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_prescription',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('paid', models.IntegerField(null=True)),
                ('debt', models.IntegerField(null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('patient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_payment',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status',
                 models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor',
                                             to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nurse',
                                            to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
