# Generated by Django 3.1.7 on 2021-05-18 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MedRec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20)),
                ('age', models.IntegerField()),
                ('passport_number', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('symptoms', models.CharField(max_length=500)),
                ('prescription', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedRec.account')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='MedRecAppointments.patientcreation')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cost', models.IntegerField(null=True)),
                ('paid', models.IntegerField(null=True)),
                ('debt', models.IntegerField(null=True)),
                ('total_amount', models.IntegerField(default=0, null=True)),
                ('patient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_payment',
                                   to='MedRecAppointments.patientcreation')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status',
                 models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor',
                                             to='MedRec.account')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nurse',
                                            to='MedRec.account')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='MedRecAppointments.patientcreation')),
            ],
        ),
    ]
