# Generated by Django 3.1.7 on 2021-05-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MedRecAppointments', '0002_auto_20210518_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcreation',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=20),
        ),
    ]
