# Generated by Django 3.1.7 on 2021-05-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MedRecAppointments', '0004_auto_20210518_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcreation',
            name='age',
            field=models.IntegerField(default=20, max_length=100),
            preserve_default=False,
        ),
    ]
