# Generated by Django 3.1.7 on 2021-05-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MedRecAppointments', '0005_patientcreation_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcreation',
            name='age',
            field=models.IntegerField(),
        ),
    ]
