# Generated by Django 3.1.7 on 2021-05-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MedRec', '0002_auto_20210517_2234'),
        ('MedRecAppointments', '0006_auto_20210518_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedRec.account'),
        ),
    ]
