# Generated by Django 3.1.7 on 2021-05-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MedRecAppointments', '0008_prescription_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='passport_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='passport_numberPrescription',
                                    to='MedRecAppointments.patientcreation'),
        ),
    ]
