# Generated by Django 3.1.7 on 2021-05-18 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('MedRecAppointments', '0009_prescription_passport_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='passport_number',
        ),
    ]
